# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Biznes\DatabaseBundle\Entity\Users:
            algorithm: bcrypt
            cost:      11

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: BiznesDatabaseBundle:Users
                property: username

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                
            logout:
                path:   /logout
                target: /
                invalidate_session: false
                
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

