# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
services:
    cartManager:
         class: Biznes\Utils\CartManager
         public: true
    userManager:
         class: Biznes\Utils\UserManager
         arguments: [ '@doctrine.orm.entity_manager' ]
         public: true